/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { Layers, Plus, Trash2, Database, Code2, Sparkles, Check, ChevronRight } from 'lucide-react';
import CodeHighlight from './CodeHighlight';
import { Column } from '../types';

export default function SchemaDesigner() {
  const [tableName, setTableName] = useState('posts');
  const [structName, setStructName] = useState('Post');
  const [columns, setColumns] = useState<Column[]>([
    { name: 'id', type: 'i32', primaryKey: true, nullable: false, unique: true },
    { name: 'title', type: 'String', primaryKey: false, nullable: false, unique: false },
    { name: 'slug', type: 'String', primaryKey: false, nullable: false, unique: true },
    { name: 'body', type: 'String', primaryKey: false, nullable: true, unique: false },
    { name: 'is_published', type: 'bool', primaryKey: false, nullable: false, unique: false, defaultValue: 'false' },
    { name: 'created_at', type: 'NaiveDateTime', primaryKey: false, nullable: false, unique: false }
  ]);

  const [rustStruct, setRustStruct] = useState('');
  const [sqlMigration, setSqlMigration] = useState('');
  const [activeTab, setActiveTab] = useState<'rust' | 'sql'>('rust');

  // Utility to map Rust types to SQL types
  const mapTypeToSql = (type: string) => {
    switch (type) {
      case 'i32': return 'INT';
      case 'i64': return 'BIGINT';
      case 'String': return 'VARCHAR(255)';
      case 'bool': return 'BOOLEAN';
      case 'f64': return 'DECIMAL(12, 2)';
      case 'NaiveDateTime': return 'TIMESTAMP';
      case 'Uuid': return 'UUID';
      default: return 'VARCHAR(255)';
    }
  };

  const addColumn = () => {
    setColumns([
      ...columns,
      {
        name: `new_col_${columns.length + 1}`,
        type: 'String',
        primaryKey: false,
        nullable: true,
        unique: false
      }
    ]);
  };

  const removeColumn = (index: number) => {
    // Keep primary key at index 0 or ensure at least one primary key is there
    if (columns[index].primaryKey && columns.filter(c => c.primaryKey).length === 1) {
      alert('Seu modelo precisa de pelo menos uma chave primária (Primary Key).');
      return;
    }
    setColumns(columns.filter((_, i) => i !== index));
  };

  const updateColumn = <K extends keyof Column>(index: number, field: K, value: Column[K]) => {
    setColumns(
      columns.map((col, i) => {
        if (i === index) {
          const newCol = { ...col, [field]: value };
          // If setting this field as a high-level primaryKey, set others to false (usually one PK)
          if (field === 'primaryKey' && value === true) {
            // PK must not be nullable
            newCol.nullable = false;
          }
          return newCol;
        }
        // If this column is updated to be the sole PK, reset others if desired
        if (field === 'primaryKey' && value === true) {
          return { ...col, primaryKey: false };
        }
        return col;
      })
    );
  };

  // Compile Rust Struct and SQL Migration code on updates
  useEffect(() => {
    // 1. Rust Struct representation
    let rust = `use rullst_orm::prelude::*;\n`;
    rust += `use chrono::NaiveDateTime;\n`;
    rust += `use uuid::Uuid;\n\n`;
    
    rust += `#[derive(ActiveRecord, Debug, Clone, Serialize, Deserialize)]\n`;
    rust += `#[table = "${tableName}"]\n`;
    
    // Find custom identifier attributes
    const pk = columns.find(c => c.primaryKey);
    if (pk && pk.name !== 'id') {
      rust += `#[primary_key = "${pk.name}"]\n`;
    }
    
    rust += `pub struct ${structName} {\n`;
    
    columns.forEach((col) => {
      let typeStr = col.type;
      if (col.nullable) {
        typeStr = `Option<${typeStr}>`;
      }
      rust += `    pub ${col.name}: ${typeStr},\n`;
    });
    
    rust += `}`;
    setRustStruct(rust);

    // 2. SQL Migration compilation
    let sql = `CREATE TABLE ${tableName} (\n`;
    const colStatements = columns.map((col) => {
      let stmt = `    ${col.name} ${mapTypeToSql(col.type)}`;
      
      if (col.primaryKey) {
        stmt += ' PRIMARY KEY';
        if (col.type === 'i32' || col.type === 'i64') {
          stmt += ' GENERATED BY DEFAULT AS IDENTITY';
        }
      } else {
        if (!col.nullable) stmt += ' NOT NULL';
        if (col.unique) stmt += ' UNIQUE';
        if (col.defaultValue !== undefined && col.defaultValue !== '') {
          const def = col.defaultValue === 'true' || col.defaultValue === 'false' || !isNaN(Number(col.defaultValue))
            ? col.defaultValue
            : `'${col.defaultValue}'`;
          stmt += ` DEFAULT ${def}`;
        }
      }
      return stmt;
    });
    
    sql += colStatements.join(',\n') + '\n);';
    setSqlMigration(sql);

  }, [tableName, structName, columns]);

  return (
    <section id="designer" className="py-20 bg-zinc-950 border-t border-zinc-900 relative">
      <div className="absolute bottom-0 right-1/4 w-[400px] h-[400px] bg-orange-600/5 rounded-full blur-[120px] pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Detail descriptor header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-orange-500/10 border border-orange-500/20 text-orange-500 text-xs font-bold uppercase tracking-widest mb-4">
            <Layers className="h-4 w-4" />
            <span>Schema Designer</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-display font-medium text-white tracking-tight text-glow-orange">
            Rust Model & Column Designer
          </h2>
          <p className="text-zinc-400 mt-4 leading-relaxed text-sm md:text-base font-sans">
            Desenhe seus modelos de banco de dados visualmente para o Rullst ORM. Nós geramos a declaração do Struct com as anotações do macromodelo e o script SQL correspondente para migração.
          </p>
        </div>

        {/* Multi-Pane designer space */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Form designer card (6 Columns) */}
          <div className="lg:col-span-6 bg-zinc-900/20 border border-zinc-800/80 rounded-xl p-6 space-y-6 box-glow-orange">
            <h3 className="font-display font-medium text-lg text-white border-b border-zinc-800/50 pb-3 flex items-center space-x-2">
              <Sparkles className="h-5 w-5 text-orange-500" />
              <span>Propriedades do Modelo</span>
            </h3>

            {/* Entity metadata inputs */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Nome do Struct Rust</label>
                <input
                  type="text"
                  value={structName}
                  onChange={(e) => setStructName(e.target.value)}
                  className="w-full bg-zinc-950 border border-zinc-800 text-xs text-white px-3 py-2.5 rounded-lg focus:border-orange-500 outline-none font-semibold"
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Tabela do Banco de Dados</label>
                <input
                  type="text"
                  value={tableName}
                  onChange={(e) => setTableName(e.target.value)}
                  className="w-full bg-zinc-950 border border-zinc-800 text-xs text-white px-3 py-2.5 rounded-lg focus:border-orange-500 outline-none font-semibold"
                />
              </div>
            </div>

            {/* Columns builder column flow */}
            <div className="space-y-3 pb-3">
              <div className="flex items-center justify-between">
                <label className="text-[10px] uppercase font-bold text-zinc-500 tracking-widest">Definição dos Campos ({columns.length})</label>
                <button
                  onClick={addColumn}
                  className="flex items-center space-x-1 px-3 py-1.5 rounded bg-orange-600 hover:bg-orange-500 text-black font-bold text-xs transition-colors cursor-pointer"
                >
                  <Plus className="h-3.5 w-3.5" />
                  <span>Novo Campo</span>
                </button>
              </div>

              {/* Columns container list */}
              <div className="space-y-2.5 max-h-[380px] overflow-y-auto pr-1">
                {columns.map((col, idx) => (
                  <div
                    key={idx}
                    className="p-3 bg-zinc-950/70 rounded-lg border border-zinc-900 flex flex-col md:flex-row md:items-center gap-3 relative group"
                  >
                    {/* Index identifier */}
                    <div className="absolute right-3 top-3 md:static text-[10px] font-mono font-extrabold text-zinc-650 bg-zinc-900 border border-zinc-805 h-6 w-6 rounded-full flex items-center justify-center">
                      {idx + 1}
                    </div>

                    {/* Column Name */}
                    <div className="flex-1 min-w-[120px]">
                      <input
                        type="text"
                        value={col.name}
                        placeholder="nome_coluna"
                        onChange={(e) => updateColumn(idx, 'name', e.target.value)}
                        className="w-full bg-zinc-900 border border-zinc-800 text-xs text-white px-2 py-1.5 rounded focus:border-orange-500 outline-none font-mono"
                      />
                    </div>

                    {/* Column Type Select */}
                    <div className="min-w-[90px]">
                      <select
                        value={col.type}
                        onChange={(e) => updateColumn(idx, 'type', e.target.value as Column['type'])}
                        className="w-full bg-zinc-900 border border-zinc-800 text-xs text-white px-2 py-1.5 rounded focus:border-orange-500 outline-none font-mono cursor-pointer"
                      >
                        <option value="i32">i32 (Int)</option>
                        <option value="i64">i64 (BigInt)</option>
                        <option value="String">String (Text)</option>
                        <option value="bool">bool (Bool)</option>
                        <option value="f64">f64 (Decimal)</option>
                        <option value="NaiveDateTime">Chrono</option>
                        <option value="Uuid">Uuid</option>
                      </select>
                    </div>

                    {/* Checkbox settings */}
                    <div className="flex items-center space-x-3.5 shrink-0">
                      <label className="flex items-center space-x-1.5 text-xs text-zinc-500 cursor-pointer select-none">
                        <input
                          type="checkbox"
                          checked={col.primaryKey}
                          onChange={(e) => updateColumn(idx, 'primaryKey', e.target.checked)}
                          className="rounded border-zinc-800 text-orange-500 bg-zinc-900 focus:ring-0 cursor-pointer"
                        />
                        <span className="font-semibold text-[11px] text-zinc-400">PK</span>
                      </label>

                      <label className="flex items-center space-x-1.5 text-xs text-zinc-500 cursor-pointer select-none">
                        <input
                          type="checkbox"
                          checked={col.nullable}
                          disabled={col.primaryKey}
                          onChange={(e) => updateColumn(idx, 'nullable', e.target.checked)}
                          className="rounded border-zinc-800 text-orange-500 bg-zinc-900 focus:ring-0 cursor-pointer"
                        />
                        <span className="font-semibold text-[11px] text-zinc-400">Null</span>
                      </label>

                      <label className="flex items-center space-x-1.5 text-xs text-zinc-500 cursor-pointer select-none">
                        <input
                          type="checkbox"
                          checked={col.unique}
                          onChange={(e) => updateColumn(idx, 'unique', e.target.checked)}
                          className="rounded border-zinc-800 text-orange-500 bg-zinc-900 focus:ring-0 cursor-pointer"
                        />
                        <span className="font-semibold text-[11px] text-zinc-400">Unq</span>
                      </label>
                    </div>

                    {/* Trash remove icon */}
                    <button
                      onClick={() => removeColumn(idx)}
                      className="absolute right-3 bottom-3 md:static text-zinc-500 hover:text-rose-500 p-1.5 rounded-lg transition-colors cursor-pointer shrink-0 md:opacity-0 md:group-hover:opacity-100"
                      title="Deletar Coluna"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>

                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Compiled Output Side-Pane (6 Columns) */}
          <div className="lg:col-span-6 flex flex-col h-[525px] bg-[#010409] border border-zinc-800/85 rounded-xl overflow-hidden shadow-xl box-glow-orange">
            
            {/* Header selection tabs */}
            <div className="px-4 bg-zinc-900/50 border-b border-zinc-800/80 flex items-center justify-between shrink-0">
              <div className="flex space-x-1 py-1.5">
                <button
                  onClick={() => setActiveTab('rust')}
                  className={`flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                    activeTab === 'rust'
                      ? 'bg-orange-500/10 text-orange-400 border border-orange-500/20'
                      : 'text-zinc-400 hover:text-white'
                  }`}
                >
                  <Code2 className="h-4 w-4" />
                  <span>Rust Struct</span>
                </button>
                <button
                  onClick={() => setActiveTab('sql')}
                  className={`flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                    activeTab === 'sql'
                      ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20'
                      : 'text-zinc-400 hover:text-white'
                  }`}
                >
                  <Database className="h-4 w-4" />
                  <span>SQL Migration</span>
                </button>
              </div>

              <div className="text-[10px] font-mono text-zinc-550 font-extrabold uppercase">
                {activeTab === 'rust' ? 'struct_post.rs' : 'migration.sql'}
              </div>
            </div>

            {/* Live compiled body */}
            <div className="flex-1 p-5 overflow-y-auto bg-[#010409] font-mono">
              {activeTab === 'rust' ? (
                <CodeHighlight code={rustStruct} language="rust" />
              ) : (
                <CodeHighlight code={sqlMigration} language="sql" />
              )}
            </div>

            {/* Code copy or setup visual panel bottom */}
            <div className="p-4 bg-zinc-950/80 border-t border-zinc-900 flex items-center justify-between text-xs shrink-0 text-zinc-500">
              <div className="flex items-center space-x-1.5 font-bold text-orange-400/90">
                <Check className="h-4 w-4 text-emerald-400" />
                <span>Rullst Macro Synthesized</span>
              </div>
              <span className="text-[10px] text-zinc-600 font-bold uppercase tracking-widest">Auto-compiled</span>
            </div>

          </div>

        </div>

      </div>
    </section>
  );
}
